import 'dart:io';

import 'package:path/path.dart' as p;

import 'catalog.dart';

const setupRelativePath = 'lib/generated/event_sdk_setup.g.dart';
const configRelativePath = 'lib/event_sdk_config.dart';
const _importMarker = '// event_sdk_cli:imports';
const _adapterMarker = '// event_sdk_cli:adapters';
const _defaultParamsMarker = '// event_sdk_cli:default_params';

Future<void> writeSetupFile({
  required String appRoot,
  required List<PlatformSpec> platforms,
}) async {
  await _writeOrUpdateConfigFile(appRoot: appRoot, platforms: platforms);

  final file = File(p.join(appRoot, setupRelativePath));
  await file.parent.create(recursive: true);

  final content = '''
// GENERATED CODE - DO NOT EDIT BY HAND
// Generated by event_sdk_cli. Configure adapters in ../event_sdk_config.dart.

import 'package:event_sdk/event_sdk.dart';

import '../event_sdk_config.dart';

/// Call once from main() before runApp.
Future<void> setupEventSdk() async {
  await EventSdk.init(
    createEventSdkAdapters(),
    config: createEventSdkConfig(),
  );
}
''';

  await file.writeAsString(content);
}

Future<void> _writeOrUpdateConfigFile({
  required String appRoot,
  required List<PlatformSpec> platforms,
}) async {
  final file = File(p.join(appRoot, configRelativePath));
  if (!file.existsSync()) {
    await file.parent.create(recursive: true);
    await file.writeAsString(_configTemplate(platforms));
    return;
  }

  var content = await file.readAsString();
  content = _ensureDefaultParamsSection(content);
  for (final platform in platforms) {
    final factoryName = _factoryName(platform.id);
    if (!content.contains('    $factoryName(),')) {
      content = content.replaceFirst(
        _adapterMarker,
        '$_adapterMarker\n    $factoryName(),',
      );
      if (!content.contains('EventAdapter $factoryName(')) {
        content += '\n\n${_factoryTemplate(platform.id)}\n';
      }
    }
    if (!content.contains(platform.importUri)) {
      content = content.replaceFirst(
        _importMarker,
        "$_importMarker\nimport '${platform.importUri}';",
      );
    }
  }
  await file.writeAsString(content);
}

Future<void> removePlatformFromConfig({
  required String appRoot,
  required Set<String> platformIds,
}) async {
  final file = File(p.join(appRoot, configRelativePath));
  if (!file.existsSync()) return;

  var content = await file.readAsString();
  for (final id in platformIds) {
    content = content.replaceFirst('    ${_factoryName(id)}(),\n', '');
  }
  await file.writeAsString(content);
}

String _configTemplate(List<PlatformSpec> platforms) {
  final imports = platforms
      .map((platform) => "import '${platform.importUri}';")
      .join('\n');
  final factories = platforms.map((platform) => _factoryTemplate(platform.id));
  final adapterFactories = platforms
      .map((platform) => '    ${_factoryName(platform.id)}(),')
      .join('\n');

  return '''
// App-owned Event SDK configuration.
//
// This file is created once and will not be overwritten by `event_sdk_cli add`.
// Replace each TODO with credentials/configuration from the vendor dashboard.

import 'package:event_sdk/event_sdk.dart';
$_importMarker
$imports

${_defaultParamsBlock()}

EventSdkConfig createEventSdkConfig() => EventSdkConfig(
  defaultParams: eventSdkDefaultParams,
);

List<EventAdapter> createEventSdkAdapters() => [
$_adapterMarker
$adapterFactories
];

${factories.join('\n\n')}
''';
}

String _defaultParamsBlock() => '''
/// Default key/value pairs sent with **every** [EventSdk.track] call
/// to **all** enabled platforms (AWS, AWS endpoint, Adjust, Firebase, Amplitude).
///
/// Edit this map in source, then change values at runtime:
/// `EventSdk.setDefaultParam('userId', 'user_123')`
/// `EventSdk.updateDefaultParams({'userType': 'premium'})`
$_defaultParamsMarker
final eventSdkDefaultParams = <String, Object?>{
  // 'source': 'mobile_app',
  // 'env': 'dev',
};
''';

String _ensureDefaultParamsSection(String content) {
  if (content.contains('eventSdkDefaultParams')) {
    if (!content.contains('createEventSdkConfig()')) {
      content = content.replaceFirst(
        'List<EventAdapter> createEventSdkAdapters()',
        '''EventSdkConfig createEventSdkConfig() => EventSdkConfig(
  defaultParams: eventSdkDefaultParams,
);

List<EventAdapter> createEventSdkAdapters()''',
      );
    }
    return content;
  }

  final insertAt = content.indexOf('List<EventAdapter> createEventSdkAdapters()');
  final block = '''
${_defaultParamsBlock()}
EventSdkConfig createEventSdkConfig() => EventSdkConfig(
  defaultParams: eventSdkDefaultParams,
);

''';
  if (insertAt == -1) {
    return '$content\n$block';
  }
  return content.substring(0, insertAt) + block + content.substring(insertAt);
}

String _factoryName(String platform) =>
    'create${platform[0].toUpperCase()}${platform.substring(1)}Adapter';

String _factoryTemplate(String platform) {
  switch (platform) {
    case 'aws':
      return '''
EventAdapter createAwsAdapter() => AwsPinpointAdapter(
  config: AwsPinpointConfig(
    // TODO: supply your Amplify / Pinpoint JSON configuration.
    amplifyConfig: 'REPLACE_WITH_AMPLIFY_CONFIGURATION',
  ),
);''';
    case 'aws_endpoint':
      return '''
EventAdapter createAws_endpointAdapter() => AwsEndpointAdapter(
  config: AwsEndpointConfig(
    // TODO: replace with your analytics HTTP endpoint URL.
    endpoint: 'REPLACE_WITH_AWS_ENDPOINT_URL',
    defaultFields: AwsEndpointDefaultFields(
      appName: 'REPLACE_WITH_APP_NAME',
      platform: 'REPLACE_WITH_PLATFORM', // e.g. Android / iOS
      appId: 'REPLACE_WITH_APP_ID',
      deviceId: 'REPLACE_WITH_DEVICE_ID',
      installId: 'REPLACE_WITH_INSTALL_ID',
      userId: 'REPLACE_WITH_USER_ID',
      appVersion: 'REPLACE_WITH_APP_VERSION',
      appEnvironment: 'REPLACE_WITH_APP_ENVIRONMENT',
      osVersion: 'REPLACE_WITH_OS_VERSION',
      deviceModel: 'REPLACE_WITH_DEVICE_MODEL',
      languageCode: 'REPLACE_WITH_LANGUAGE_CODE',
      userType: 'REPLACE_WITH_USER_TYPE',
      gaid: 'REPLACE_WITH_GAID',
    ),
  ),
);''';
    case 'adjust':
      return '''
EventAdapter createAdjustAdapter() => AdjustAdapter(
  config: AdjustEventConfig(
    // TODO: replace with your Adjust app token and event-token map.
    appToken: 'REPLACE_WITH_ADJUST_APP_TOKEN',
    eventTokens: const {
      // 'signup_completed': 'adjust_event_token',
    },
  ),
);''';
    case 'firebase':
      return '''
EventAdapter createFirebaseAdapter() => FirebaseAnalyticsAdapter();

// TODO: initialize Firebase in main() before setupEventSdk(). See
// https://firebase.google.com/docs/flutter/setup for flutterfire configure.''';
    case 'amplitude':
      return '''
EventAdapter createAmplitudeAdapter() => AmplitudeAdapter(
  config: const AmplitudeConfig(
    // TODO: replace with your Amplitude project API key.
    apiKey: 'REPLACE_WITH_AMPLITUDE_API_KEY',
  ),
);''';
    default:
      throw ArgumentError('No config template for "$platform".');
  }
}

Future<Set<String>> readEnabledPlatforms(String appRoot) async {
  final configFile = File(p.join(appRoot, configRelativePath));
  if (!configFile.existsSync()) return {};

  final config = await configFile.readAsString();
  final adapterListStart = config.indexOf('createEventSdkAdapters() => [');
  final adapterListEnd = config.indexOf('];', adapterListStart);
  if (adapterListStart == -1 || adapterListEnd == -1) return {};
  final adapterList = config.substring(adapterListStart, adapterListEnd);
  final enabled = <String>{};
  for (final id in supportedPlatforms.keys) {
    if (adapterList.contains(_factoryName(id))) enabled.add(id);
  }
  return enabled;
}
