import 'dart:io';

import 'package:path/path.dart' as p;

import 'catalog.dart';

const setupRelativePath = 'lib/generated/event_sdk_setup.g.dart';
const configRelativePath = 'lib/event_sdk_config.dart';
const _importMarker = '// event_sdk_cli:imports';
const _adapterMarker = '// event_sdk_cli:adapters';

Future<void> writeSetupFile({
  required String appRoot,
  required List<PlatformSpec> platforms,
}) async {
  await _writeOrUpdateConfigFile(appRoot: appRoot, platforms: platforms);

  final file = File(p.join(appRoot, setupRelativePath));
  await file.parent.create(recursive: true);

  final content = '''
// GENERATED CODE - DO NOT EDIT BY HAND
// Generated by event_sdk_cli. Configure adapters in ../event_sdk_config.dart.

import 'package:event_sdk/event_sdk.dart';

import '../event_sdk_config.dart';

/// Call once from main() before runApp.
Future<void> setupEventSdk() async {
  await EventSdk.init(createEventSdkAdapters());
}
''';

  await file.writeAsString(content);
}

Future<void> _writeOrUpdateConfigFile({
  required String appRoot,
  required List<PlatformSpec> platforms,
}) async {
  final file = File(p.join(appRoot, configRelativePath));
  if (!file.existsSync()) {
    await file.parent.create(recursive: true);
    await file.writeAsString(_configTemplate(platforms));
    return;
  }

  var content = await file.readAsString();
  for (final platform in platforms) {
    final factoryName = _factoryName(platform.id);
    if (!content.contains('    $factoryName(),')) {
      content = content.replaceFirst(
        _adapterMarker,
        '$_adapterMarker\n    $factoryName(),',
      );
      if (!content.contains('EventAdapter $factoryName(')) {
        content += '\n\n${_factoryTemplate(platform.id)}\n';
      }
    }
    if (!content.contains(platform.importUri)) {
      content = content.replaceFirst(
        _importMarker,
        "$_importMarker\nimport '${platform.importUri}';",
      );
    }
  }
  await file.writeAsString(content);
}

Future<void> removePlatformFromConfig({
  required String appRoot,
  required Set<String> platformIds,
}) async {
  final file = File(p.join(appRoot, configRelativePath));
  if (!file.existsSync()) return;

  var content = await file.readAsString();
  for (final id in platformIds) {
    content = content.replaceFirst('    ${_factoryName(id)}(),\n', '');
  }
  await file.writeAsString(content);
}

String _configTemplate(List<PlatformSpec> platforms) {
  final imports = platforms
      .map((platform) => "import '${platform.importUri}';")
      .join('\n');
  final factories = platforms.map((platform) => _factoryTemplate(platform.id));
  final adapterFactories = platforms
      .map((platform) => '    ${_factoryName(platform.id)}(),')
      .join('\n');

  return '''
// App-owned Event SDK configuration.
//
// This file is created once and will not be overwritten by `event_sdk_cli add`.
// Replace each TODO with credentials/configuration from the vendor dashboard.

import 'package:event_sdk/event_sdk.dart';
$_importMarker
$imports

List<EventAdapter> createEventSdkAdapters() => [
$_adapterMarker
$adapterFactories
];

${factories.join('\n\n')}
''';
}

String _factoryName(String platform) =>
    'create${platform[0].toUpperCase()}${platform.substring(1)}Adapter';

String _factoryTemplate(String platform) {
  switch (platform) {
    case 'aws':
      return '''
EventAdapter createAwsAdapter() => AwsPinpointAdapter(
  config: AwsPinpointConfig(
    // TODO: supply your Amplify / Pinpoint JSON configuration.
    amplifyConfig: 'REPLACE_WITH_AMPLIFY_CONFIGURATION',
  ),
);''';
    case 'adjust':
      return '''
EventAdapter createAdjustAdapter() => AdjustAdapter(
  config: AdjustEventConfig(
    // TODO: replace with your Adjust app token and event-token map.
    appToken: 'REPLACE_WITH_ADJUST_APP_TOKEN',
    eventTokens: const {
      // 'signup_completed': 'adjust_event_token',
    },
  ),
);''';
    case 'firebase':
      return '''
EventAdapter createFirebaseAdapter() => FirebaseAnalyticsAdapter();

// TODO: initialize Firebase in main() before setupEventSdk(). See
// https://firebase.google.com/docs/flutter/setup for flutterfire configure.''';
    case 'amplitude':
      return '''
EventAdapter createAmplitudeAdapter() => AmplitudeAdapter(
  config: const AmplitudeConfig(
    // TODO: replace with your Amplitude project API key.
    apiKey: 'REPLACE_WITH_AMPLITUDE_API_KEY',
  ),
);''';
    default:
      throw ArgumentError('No config template for "$platform".');
  }
}

Future<Set<String>> readEnabledPlatforms(String appRoot) async {
  final configFile = File(p.join(appRoot, configRelativePath));
  if (!configFile.existsSync()) return {};

  final config = await configFile.readAsString();
  final adapterListStart = config.indexOf('createEventSdkAdapters() => [');
  final adapterListEnd = config.indexOf('];', adapterListStart);
  if (adapterListStart == -1 || adapterListEnd == -1) return {};
  final adapterList = config.substring(adapterListStart, adapterListEnd);
  final enabled = <String>{};
  for (final id in supportedPlatforms.keys) {
    if (adapterList.contains(_factoryName(id))) enabled.add(id);
  }
  return enabled;
}
