import 'dart:io';

import 'package:path/path.dart' as p;

import 'catalog.dart';

const setupRelativePath = 'lib/generated/event_sdk_setup.g.dart';

Future<void> writeSetupFile({
  required String appRoot,
  required List<PlatformSpec> platforms,
}) async {
  final file = File(p.join(appRoot, setupRelativePath));
  await file.parent.create(recursive: true);

  final imports = <String>{
    "import 'package:event_sdk/event_sdk.dart';",
    for (final platform in platforms) "import '${platform.importUri}';",
  }.toList()
    ..sort();

  final adapters = platforms
      .map((platform) => '    ${platform.adapterExpression},')
      .join('\n');

  final content = '''
// GENERATED CODE - DO NOT EDIT BY HAND
// Generated by event_sdk_cli. Replace UnimplementedError configs with real values.

${imports.join('\n')}

/// Call once from main() before runApp.
Future<void> setupEventSdk() async {
  await EventSdk.init([
$adapters
  ]);
}
''';

  await file.writeAsString(content);
}

Future<Set<String>> readEnabledPlatforms(String appRoot) async {
  final file = File(p.join(appRoot, setupRelativePath));
  if (!file.existsSync()) return {};

  final text = await file.readAsString();
  final enabled = <String>{};
  for (final id in supportedPlatforms.keys) {
    if (text.contains(supportedPlatforms[id]!.importUri) ||
        text.contains(supportedPlatforms[id]!.packageName)) {
      enabled.add(id);
    }
  }
  // Fallback: detect adapter class names.
  if (text.contains('AwsPinpointAdapter')) enabled.add('aws');
  if (text.contains('AdjustAdapter')) enabled.add('adjust');
  return enabled;
}
