name: aws_endpoint_sdk
description: HTTP endpoint adapter for event_sdk (MobileTrackingEvent format).
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  event_sdk:
    git:
      url: https://github.com/PranavBlob/flutter_blob_events.git
      path: packages/event_sdk
      ref: event_sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
